name: CI Build / Test

on:
  push:
    branches: [ "master", "ci" ]
  pull_request:
    branches: [ "master" ]

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Install Dependencies
      working-directory: ./server
      run: go mod tidy

    - name: Build
      working-directory: ./server
      run: go build

    - name: Lint
      working-directory: ./server
      run: go vet ./...

    - name: Test
      working-directory: ./server
      run: go test -v ./...
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
  
      - name: Install Dependencies
        working-directory: ./frontend
        run: bun install
  
      - name: Lint
        working-directory: ./frontend
        run: bun lint
  
      - name: Test
        working-directory: ./frontend
        run: bun test